# baseURL = "https://davidsass.io/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"
title = "David Sass"
copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "David Sass"
  headline = "Speaker, SRE, MCT, Dreamer, Legend"
  image = "img/author.jpg"  # path relative to static directory

  links = [
    { link = "https://kolislab.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    { credly = "https://www.credly.com/users/david-sass" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/sassdawe" },
    { gitlab = "https://gitlab.com/sassdawe" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/sassdawe" },
    { mastodon = "https://infosec.exchange/@sassdawe" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    { poshgallery = "https://www.powershellgallery.com/profiles/sassdawe" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    { sessionize = "https://sessionize.com/david-sass/" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://www.youtube.com/playlist?list=PLeTb1wUwL7st2qR43hh3Xwgm4DKbLAY20" },
    { email = "mailto:hello@davidsass.io" }
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"